version: "3.8"

services:
  sovauto:
    build: .
    container_name: sovauto
    restart: always

    ports:
      - "6000:5000"

    env_file:
      - .env

    environment:
      - NODE_ENV=production